server:
  port: 9999

spring:
  application:
    name: '@artifactId@'
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:demo-nacos}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:${spring.application.name}-@profiles.active@.yml



